name: Periodic Model Calibration

on:
  schedule:
    - cron: "0 0 * * *" #minutes, hours, day, month, day of week

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create directories
        run: |
          mkdir -p models
          mkdir -p metrics

      - name: Generate and Store Timestamp
        run: |
          timestamp=$(date '+%Y%m%d%H%M%S')
          echo "$timestamp" > timestamp.txt
        id: timestamp

      - name: Check File Permissions for iris
        run: |
          ls -l ./src/train_iris.py
          ls -l ./src/train_wine.py

      - name: Set File Permissions
        run: |
          chmod +x ./src/train_iris.py
          chmod +x ./src/train_wine.py

      - name: Retrain Model
        run: |
          timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
          python ./src/train_iris.py --timestamp "$timestamp"
          python ./src/train_wine.py --timestamp "$timestamp"

      - name: Upload Iris Model
        uses: actions/upload-artifact@v3
        with:
          name: iris-model-${{ steps.timestamp.outputs.timestamp }}
          path: src/model/iris_model.pkl

      - name: Upload Wine Model
        uses: actions/upload-artifact@v3
        with:
          name: wine-model-${{ steps.timestamp.outputs.timestamp }}
          path: src/model/wine_model.pkl

      - name: Commit and Push Models
        run: |
          git config --global user.email "YOUR_EMAIL"
          git config --global user.name "YOUR_NAME"
          git add models/
          git add metrics/
          git diff --staged --quiet || git commit -m "Update models - ${{ steps.timestamp.outputs.timestamp }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Evaluate Model and Log Metrics
    #   run: |
    #     timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
    #     python ./src/evaluate_model.py  --timestamp "$timestamp" # Assuming you have a script for model evaluation
    #     metrics_filename="${timestamp}_metrics.json"
    #     mv $metrics_filename $GITHUB_WORKSPACE/metrics/$metrics_filename
    #   continue-on-error: false  # Continue even if evaluation fails

    # - name: Store and Version the New Model
    #   run: |
    #     timestamp=$(cat timestamp.txt)
    #     model_filename="model_${timestamp}_dt_model.joblib"
    #     mv $model_filename $GITHUB_WORKSPACE/models/$model_filename

    # - name: Commit and Push Changes
    #   run: |
    #     git config --global user.email "26876927+raminmohammadi@users.noreply.github.com"
    #     git config --global user.name "raminmohammadi"
    #     git add $GITHUB_WORKSPACE/metrics/$metrics_filename $GITHUB_WORKSPACE/models/$model_filename
    #     git commit -m "Add metrics and updated model"
    #     git push
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
